# Build a Perceptron

## Objectives & Summary 

Objective: extend your perceptron ~~by measuring the **accuracy** of a perceptron.~~
by minimizing the weights and yet having the perceptron fire. 

Summary: 

- Build a `Perceptron` class.
- Write some error handling. 

            try:
            self.threshold = float(threshold)
        except ValueError:
            print("Threshold must be numeric.")
            
- Minimize weights for a single perceptron.




In [1]:
vec_1 = range(1000)
vec_2 = range(1000)

In [2]:
import numpy as np

In [3]:
%%timeit

sum([v_1_i*v_2_i for v_1_i, v_2_i in zip(vec_1, vec_2)])

1000 loops, best of 3: 201 µs per loop


In [4]:
%%timeit
np.array(vec_1).dot(vec_2)

10000 loops, best of 3: 74.5 µs per loop


<img src="assets/perceptron.png" width="500px">

## Dot Product

$$\vec{x} \cdot \vec{\beta} = \sum x_i\beta_i = x_1\beta_1 + \dots + x_n\beta_n$$

## Step Function

\begin{align}
   f(x) = \left\{
     \begin{array}{lr}
       1 &: x > \beta_0\\
       0 &: x \not\gt \beta_0
     \end{array}
   \right.
\end{align}

## Size of the Perceptron

The "size" of the perceptron will be given by the $\ell2$-norm of the wieghts

$$\ell2\left(\vec\beta\right) = \sqrt{\beta_1^2 +\dots+\beta_n^2}$$

Remember, the $\ell2$-norm is like the "Euclidean" distance i.e. the length of a hypotenuse in a right triangle.

In [5]:
import numpy as np
from numpy.linalg import norm

class Perceptron:
                
    def __init__(self, weights, threshold):
        
        self.weights = np.array(weights)
        
        try:
            self.threshold = float(threshold)
        except ValueError:
            print("Threshold must be numeric.")
          
    
    def activate(self,inputs):
        '''Takes in @param inputs, a list of numbers.
        @return the output of a threshold perceptron with
        given weights, threshold, and inputs.
        ''' 

        #TODO: calculate the strength with which the perceptron fires        
        #HINT: Use a dot product
        energy = np.dot(self.weights, inputs)

        #TODO: return 0 or 1 based on the threshold         
        #HINT: Use a Step Function        
        return 1 if energy >= self.threshold else 0

    def size_(self):
        #TODO: calculate the size of the perceptron (the size of the weights vector) using the l2-norm
        return norm(self.weights)


In [16]:
ptron = Perceptron((1,-2,3,1),4)
try: 
    assert ptron.activate((1,0,1,1)) == 1
except AssertionError:
    print("Are you sure you have implemented your perceptron correctly?")

ptron.size_()

3.872983346207417

## Minimizing Weights

<img src="assets/perceptron_instance_1.png" width="500px">

### 1. Find a set of weights that make this return a 1

In [17]:
weights = (0,-2,0,0)
inputs = (1,-3,5,5)
ptron_1 = Perceptron(weights,6)

try:
    assert ptron_1.activate(inputs) == 1
except AssertionError:
    print("Looks like your weights aren't strong enough.")

### 2. Calculate the Size of the Perceptron

In [18]:
ptron_1.size_()

2.0

### 3. See if you can find a smaller Perceptron that returns a 1

In [19]:
weights = (.1,-.2,.56,.56)
ptron_2 = Perceptron(weights,6)
ptron_2.activate(inputs), ptron_2.size_()

(1, 0.82292162445763939)

In [20]:
weights = (.15,-.15,.11,.15)
ptron_3 = Perceptron(weights,6)
ptron_3.activate(inputs), ptron_2.size_()

(0, 0.82292162445763939)

In [21]:
weights = (0,-.2,.56,.52)
ptron_Anna = Perceptron(weights,6)
ptron_Anna.activate(inputs), ptron_Anna.size_()

(1, 0.78993670632526003)

In [22]:
weights = (.11,-.3,.5,.5)
ptron_Mazdak = Perceptron(weights,6)
ptron_Mazdak.activate(inputs), ptron_Mazdak.size_()

(1, 0.7759510293826537)

## Accuracy

For the Perceptron described with the given `weights` and `threshold`, calculate its accuracy for the given set of `inputs` and `actual` values.

<img src="assets/perceptron_instance_2.png" width="500px">

In [36]:
weights = (-3,4,1,.3)
threshold = 2

inputs = [(-0.6 ,  0.78,  1.32,  0.88),
          (-1.94, -1.42,  0.76,  0.75),
          ( 0.02,  0.77,  0.62, -1.4 ),
          (-0.46, -0.  , -1.24,  0.37),
          ( 0.2 ,  0.52, -1.48, -0.28),
          ( 1.55, -1.44, -0.53,  0.67),
          (-0.22, -0.96, -1.76, -1.35),
          (-1.23,  0.28,  0.61, -0.23),
          ( 0.74, -1.34, -0.76,  0.07),
          (-0.99,  0.88,  0.84,  0.1 )]

actual = [1, 1, 0, 1, 0, 1, 1, 1, 0, 1]

# TODO: Make a new Perceptron with the given weights and threshold

# TODO: Trigger the Perceptron for each input vector

# TODO: Compare the predicted value i.e. the output to the corresponding actual value

# TODO: Measure the accuracy of this set of weights


### See if Changing the Weights via Guess and Check you can get a higher accuracy

In [37]:
ptron_4 = Perceptron(weights, threshold)

In [32]:
ptron_4.activate(inputs[0]) == actual[0]

True

In [39]:
predicted = [ptron_4.activate(inp) for inp in inputs]
predicted

[1, 0, 1, 0, 0, 0, 0, 1, 0, 1]

In [46]:
ptron.weights = np.array(ptron.weights) - 0.1*np.array(inp)

In [42]:
np.mean([act == pred for act, pred in zip(actual, predicted)])

0.5

In [43]:
def fire_and_measure():
    predicted = [ptron.activate(inp) for inp in inputs]
    return np.mean([act == pred for act, pred in zip(actual, predicted)])

In [45]:
fire_and_measure()

0.29999999999999999

In [48]:
for i in range(5):
    for inp in inputs:
        ptron.weights = np.array(ptron.weights) - 0.1*np.array(inp)
        print (ptron.weights)
    fire_and_measure()

[ 1.452 -1.973  2.946  0.944]
[ 1.646 -1.831  2.87   0.869]
[ 1.644 -1.908  2.808  1.009]
[ 1.69  -1.908  2.932  0.972]
[ 1.67 -1.96  3.08  1.  ]
[ 1.515 -1.816  3.133  0.933]
[ 1.537 -1.72   3.309  1.068]
[ 1.66  -1.748  3.248  1.091]
[ 1.586 -1.614  3.324  1.084]
[ 1.685 -1.702  3.24   1.074]
[ 1.745 -1.78   3.108  0.986]
[ 1.939 -1.638  3.032  0.911]
[ 1.937 -1.715  2.97   1.051]
[ 1.983 -1.715  3.094  1.014]
[ 1.963 -1.767  3.242  1.042]
[ 1.808 -1.623  3.295  0.975]
[ 1.83  -1.527  3.471  1.11 ]
[ 1.953 -1.555  3.41   1.133]
[ 1.879 -1.421  3.486  1.126]
[ 1.978 -1.509  3.402  1.116]
[ 2.038 -1.587  3.27   1.028]
[ 2.232 -1.445  3.194  0.953]
[ 2.23  -1.522  3.132  1.093]
[ 2.276 -1.522  3.256  1.056]
[ 2.256 -1.574  3.404  1.084]
[ 2.101 -1.43   3.457  1.017]
[ 2.123 -1.334  3.633  1.152]
[ 2.246 -1.362  3.572  1.175]
[ 2.172 -1.228  3.648  1.168]
[ 2.271 -1.316  3.564  1.158]
[ 2.331 -1.394  3.432  1.07 ]
[ 2.525 -1.252  3.356  0.995]
[ 2.523 -1.329  3.294  1.135]
[ 2.569 -1.329