## Imperative v Functional Programming

**Imperative**, the state of the computation is reflected by the values of the variables in the various namespaces.


In [2]:
spam = 1
eggs = 2

In [3]:
vars()

{'In': ['', u'vars()', u'spam = 1\neggs = 2', u'vars()'],
 'MatplotlibFinder': __main__.MatplotlibFinder,
 'Out': {1: {...}},
 '_': {...},
 '_1': {...},
 '__': '',
 '___': '',
 '__builtin__': <module '__builtin__' (built-in)>,
 '__builtins__': <module '__builtin__' (built-in)>,
 '__doc__': 'Startup script for IPython kernel.\n\nInstalls an import hook to configure the matplotlib backend on the fly.\n\nOriginally from @minrk at \nhttps://github.com/minrk/profile_default/blob/master/startup/mplimporthook.py\nRepurposed for docker-stacks to address repeat bugs like\nhttps://github.com/jupyter/docker-stacks/issues/235.\n',
 '__name__': '__main__',
 '__package__': None,
 '_dh': [u'/home/jovyan/work/curriculum/week-02/2.4-Lesson-Advanced-Lambda-Functions'],
 '_i': u'spam = 1\neggs = 2',
 '_i1': u'vars()',
 '_i2': u'spam = 1\neggs = 2',
 '_i3': u'vars()',
 '_ih': ['', u'vars()', u'spam = 1\neggs = 2', u'vars()'],
 '_ii': u'vars()',
 '_iii': u'',
 '_oh': {1: {...}},
 '_sh': <module 'IPython.co

Each new statement changes the state by adding, changing, or removing a variable.

With **functional** programming, instead of manipulating a state, we are evaluating functions.

Each function evaluation creates a new object or objects from existing objects. 

To dig into these concepts, let us begin thinking about functions as their own type.

In [4]:
type(len)

builtin_function_or_method

In [5]:
def say_hi(name):
    print "Hi, " + name + '!'

In [6]:
type(say_hi)

function

In [7]:
def execute_me(function):    
    function('Kermit')

In [18]:
say_hi('Joshua')

Hi, Joshua!


In [20]:
print(execute_me(len))

None


In [8]:
execute_me(say_hi)

Hi, Kermit!


### Lambda functions gave us Anonymous Functions

We can use these anonymous functions as we are passing our functions about.

In [10]:
incr_2 = make_incrementor(2)

In [11]:
type(incr_2)

function

In [12]:
print(incr_2(10))
print(incr_2(14))

12
16


In [13]:
incr_12 = make_incrementor(12)
print(incr_12(10))
print(incr_12(14))

22
26


In [9]:
def make_incrementor(n): 
    return lambda x: x + n

In [15]:
def make_exponentiator(n):
    return lambda x: x**n

In [16]:
pow_2 = make_exponentiator(2)
pow_2(9)

81

In [24]:
def pow_3(x):
    return x**3

In [27]:
make_exponentiator(3)(2) == pow_3(2)

False

### Let's create a truly anonymous function

In [14]:
print(make_incrementor(22)(33))

55


## First Steps in Functional Programming

In [28]:
type(filter), type(map), type(reduce)

(builtin_function_or_method,
 builtin_function_or_method,
 builtin_function_or_method)

### `filter`

In [31]:
def mult_of_3(x):
    return x % 3 == 0

mult_of_3(5)

False

In [32]:
print(filter(lambda x: x % 3 == 0, this_list))

[18, 9, 24, 12, 27]


`filter()` calls our lambda function for each element of the list, and returns a new list that contains only those elements for which the function returned `True`. 

In this case, we get a list of all elements that are multiples of 3. 

The expression `x % 3 == 0` computes the remainder of `x` divided by `3` and compares the result with `0` (which is true if `x` is evenly divisible by `3`).

### `map`

In [33]:
print(map(lambda x: x * 2 + 10, this_list))

[14, 46, 28, 54, 44, 58, 26, 34, 64]


`map()` is used to convert our list. 

The given function is called for every element in the original list, and a new list is created which contains the return values from our lambda function. 

In this case, it computes `2 * x + 10` for every element.

### `reduce`

`reduce()` is somewhat special. 

The "worker function" for this one must accept two arguments (we've called them x and y here), not just one.

The function is called with the first two elements from the list, then with the result of that call and the third element, and so on, until all of the list elements have been handled. 

This means that our function is called n-1 times if the list contains n elements. The return value of the last call is the result of the reduce() construct.

In [29]:
this_list = [2, 18, 9, 22, 17, 24, 8, 12, 27]

In [35]:
sum(this_list)

139

In [34]:
print(reduce(lambda x,y: x+y, this_list))

139




![](assets/images/reduce.gif)

### Lengths of Words

In [36]:
sentence = 'It is raining cats and dogs'
words = sentence.split()
print(words)

['It', 'is', 'raining', 'cats', 'and', 'dogs']


In [37]:
lengths = map(lambda word: len(word), words)
print(lengths)

[2, 2, 7, 4, 3, 4]


### Compute Primes with a Filter

In [38]:
nums = range(2, 50)
for i in range(2, 8): 
    nums = filter(lambda x: x == i or x % i, nums)
    print(nums)

[2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47, 49]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47, 49]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


In [39]:
4 % 2 == False, 5 % 2 == True

(True, True)

In [40]:
this_list = ['ghost','nippy','woozy','comparison','correct','leather','valuable',
             'spooky','cute','cowardly','effect','tricky','march','fence','fail',
             'short','paste','selection','thunder','absorbed','use','encouraging',
             'horn','drab','parched']
this_list

['ghost',
 'nippy',
 'woozy',
 'comparison',
 'correct',
 'leather',
 'valuable',
 'spooky',
 'cute',
 'cowardly',
 'effect',
 'tricky',
 'march',
 'fence',
 'fail',
 'short',
 'paste',
 'selection',
 'thunder',
 'absorbed',
 'use',
 'encouraging',
 'horn',
 'drab',
 'parched']

In [41]:
this_list.sort(key=lambda word: len(word))
this_list

['use',
 'cute',
 'fail',
 'horn',
 'drab',
 'ghost',
 'nippy',
 'woozy',
 'march',
 'fence',
 'short',
 'paste',
 'spooky',
 'effect',
 'tricky',
 'correct',
 'leather',
 'thunder',
 'parched',
 'valuable',
 'cowardly',
 'absorbed',
 'selection',
 'comparison',
 'encouraging']

In [42]:
this_list.sort(key=lambda word: word[-1])
this_list

['drab',
 'parched',
 'absorbed',
 'use',
 'cute',
 'fence',
 'paste',
 'valuable',
 'encouraging',
 'march',
 'fail',
 'horn',
 'selection',
 'comparison',
 'leather',
 'thunder',
 'ghost',
 'short',
 'effect',
 'correct',
 'nippy',
 'woozy',
 'spooky',
 'tricky',
 'cowardly']

In [44]:
import numpy as np
this_list.sort(key=lambda word: np.mean([ord(letter) for letter in word]))
this_list

['drab',
 'fence',
 'fail',
 'effect',
 'parched',
 'absorbed',
 'march',
 'valuable',
 'leather',
 'encouraging',
 'selection',
 'correct',
 'paste',
 'cute',
 'comparison',
 'cowardly',
 'thunder',
 'horn',
 'ghost',
 'tricky',
 'use',
 'short',
 'nippy',
 'spooky',
 'woozy']

## The Inner Product or Dot Product

$$\mathbf v \cdot \mathbf w = v_1w_1 + v_2w_2 +\dots + v_nw_n = \sum_{i=1}^n v_iw_i$$

For example, consider $\mathbf v = \left(\begin{matrix}1\\2\\3\\4\\5\end{matrix}\right)$ and $\mathbf w = \left(\begin{matrix}1\\-1\\1\\-1\\1\end{matrix}\right)$.


Then $\mathbf v \cdot \mathbf w$ is
$$(1,2,3,4,5)\cdot(1,-1,1,-1,1)=1\cdot1+2\cdot-1+3\cdot1+4\cdot-1+5\cdot1=3$$

Let's use `zip`, `map`, and `reduce` to calculate a dot product.

$$\mathbf v \cdot \mathbf w  = \sum_{i=1}^n v_iw_i$$

1. make a list of $v_iw_i$
2. sum this list

In [45]:
v = (1,2,3,4,5)
w = (1,-1,1,-1,1)

In [46]:
VERBOSE = True

def dot_product_via_for_loop(vector_1, vector_2):
    
    v_iw_i = list()    
    for v1_i, v_2_i in zip(vector_1, vector_2):
        v_iw_i.append(v1_i*v_2_i)
        
    if VERBOSE: print(v_iw_i)
        
    dot_product = 0
    
    for i in v_iw_i:
        dot_product += i
    return dot_product

In [47]:
dot_product_via_for_loop(v, w)

[1, -2, 3, -4, 5]


3

In [51]:
def dot_product_via_map_reduce(vector_1, vector_2):
    zipped_vectors = zip(vector_1, vector_2)
    
    if VERBOSE: print zipped_vectors
        
    v_iw_i = map(lambda i: i[0]*i[1], zipped_vectors)

    if VERBOSE: print v_iw_i    
    dot_product = reduce(lambda x, y: x+y, v_iw_i)
    
    return dot_product

In [52]:
dot_product_via_map_reduce(v, w)

[(1, 1), (2, -1), (3, 1), (4, -1), (5, 1)]
[1, -2, 3, -4, 5]


3

In [53]:
dot_product = lambda vector_1, vector_2 : sum([v_i*w_i for v_i, w_i in zip(vector_1, vector_2)])

In [54]:
dot_product(v,w)

3

In [55]:
def dot_product_readable(vector_1, vector_2):
    return sum([v_i*w_i for v_i, w_i in zip(vector_1, vector_2)])

In [57]:
dot_product_readable(v, w)

3

In [58]:
np.dot(v, w)

3

## Implement a Dot Product that will work for any two vectors of the same size

#### Bonus: Add Error Handling if a dot product is attempted on vectors of different sizes

In [60]:
u = (1,2,3,4)
np.dot(u, v)

ValueError: shapes (4,) and (5,) not aligned: 4 (dim 0) != 5 (dim 0)

## Sort Vectors Based On Their Length

The length of the vector, $\mathbf v$ is defined as

$$||\mathbf v||= \sqrt{\mathbf v \cdot \mathbf v}$$

You have seen this before:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pythagorean.svg/260px-Pythagorean.svg.png)

$$\left|\left|(a,b)\right|\right| = c$$

In [62]:
vectors_in_R_3 = [
    (1,-2,1),
    (2,3,1),
    (-3,1,-2),
    (2,2,2),
    (-2,4,0),
    (-2,1,5)
]

In [63]:
vector_length = lambda vec: np.sqrt(dot_product(vec, vec))

if VERBOSE: print(vectors_in_R_3)
    
vectors_in_R_3.sort(key=vector_length)

if VERBOSE: print(vectors_in_R_3)
    
print(map(vector_length, vectors_in_R_3))


[(1, -2, 1), (2, 3, 1), (-3, 1, -2), (2, 2, 2), (-2, 4, 0), (-2, 1, 5)]
[(1, -2, 1), (2, 2, 2), (2, 3, 1), (-3, 1, -2), (-2, 4, 0), (-2, 1, 5)]
[2.4494897427831779, 3.4641016151377544, 3.7416573867739413, 3.7416573867739413, 4.4721359549995796, 5.4772255750516612]


In [64]:
vectors_in_R_2 = [
    (1,1),
    (2,1),
    (-3,-2),
    (2,2),
    (-2,0),
    (-2,5)
]

### Unit Vectors

A unit vector is a vector of length 1. We write a unit vector with a hat 

$$\mathbf {\hat v} = \frac{\mathbf v}{||\mathbf v||}$$

In [65]:
unit_vector = lambda vec: vec/vector_length(vec)

In [66]:
unit_vector(vectors_in_R_2[0])

array([ 0.70710678,  0.70710678])

In [67]:
map(lambda v: unit_vector(v), vectors_in_R_2)

[array([ 0.70710678,  0.70710678]),
 array([ 0.89442719,  0.4472136 ]),
 array([-0.83205029, -0.5547002 ]),
 array([ 0.70710678,  0.70710678]),
 array([-1.,  0.]),
 array([-0.37139068,  0.92847669])]

## The Cosine Formula


The cosine of the angle between two vectors is given by the following function:

$$\cos \theta = \mathbf{\hat v}\cdot\mathbf{\hat w} = \frac{\mathbf v}{||\mathbf v||}\cdot\frac{\mathbf w}{||\mathbf w||}$$

### Write a lambda function implementing the cosine function